In [2]:
import numpy as np

# Elementwise Operations

**1. Basic Operations**

**with scalars**

In [3]:
a = np.array([1, 2, 3, 4]) #create an array

a + 1

array([2, 3, 4, 5])

In [4]:
a ** 2

array([ 1,  4,  9, 16])

**All arithmetic operates elementwise**

In [7]:
b = np.ones(4)
print(a)
print(b)
a - b

[1 2 3 4]
[1. 1. 1. 1.]


array([0., 1., 2., 3.])

In [8]:
a * b

array([1., 2., 3., 4.])

In [9]:
# Matrix multiplication

c = np.diag([1, 2, 3, 4])

print(c * c)
print("*****************")
print(c.dot(c))

[[ 1  0  0  0]
 [ 0  4  0  0]
 [ 0  0  9  0]
 [ 0  0  0 16]]
*****************
[[ 1  0  0  0]
 [ 0  4  0  0]
 [ 0  0  9  0]
 [ 0  0  0 16]]


**comparisions**

In [10]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 2, 2, 4])
a == b

array([False,  True, False,  True])

In [11]:
a > b

array([False, False,  True, False])

In [12]:
#array-wise comparisions
a = np.array([1, 2, 3, 4])
b = np.array([5, 2, 2, 4])
c = np.array([1, 2, 3, 4])

np.array_equal(a, b)

False

In [13]:
np.array_equal(a, c)

True

**Logical Operations**

In [14]:
a = np.array([1, 1, 0, 0], dtype=bool)
b = np.array([1, 0, 1, 0], dtype=bool)

np.logical_or(a, b)

array([ True,  True,  True, False])

In [15]:
np.logical_and(a, b)

array([ True, False, False, False])

**Transcendental functions:**

In [19]:
a = np.arange(5)
print(a)
np.sin(a)

[0 1 2 3 4]


array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [17]:
np.log(a)

<ipython-input-17-89b6b8e53c58>:1: RuntimeWarning: divide by zero encountered in log
  np.log(a)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436])

In [18]:
np.exp(a)   #evaluates e^x for each element in a given input

array([ 1.        ,  2.71828183,  7.3890561 , 20.08553692, 54.59815003])

**Shape Mismatch**

In [20]:
a = np.arange(4)
print(a)
a + np.array([1, 2])

[0 1 2 3]


ValueError: operands could not be broadcast together with shapes (4,) (2,) 

# Basic Reductions

**computing sums**

In [21]:
x = np.array([1, 2, 3, 4])
np.sum(x)

10

In [22]:
#sum by rows and by columns

x = np.array([[1, 1], [2, 2]])
x

array([[1, 1],
       [2, 2]])

In [23]:
x.sum(axis=0)   #columns first dimension

array([3, 3])

In [24]:
x.sum(axis=1)  #rows (second dimension)

array([2, 4])

**Other reductions**

In [25]:
x = np.array([1, 3, 2])
x.min()

1

In [26]:
x.max()

3

In [27]:
x.argmin()# index of minimum element

0

In [28]:
x.argmax()# index of maximum element

1

**Logical Operations**

In [29]:
np.all([True, True, False])

False

In [30]:
np.any([True, False, False])

True

In [31]:
#Note: can be used for array comparisions
a = np.zeros((50, 50))
print(a)
np.any(a != 0)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


False

In [32]:
np.all(a == a)

True

**Statistics**

In [34]:
x = np.array([1, 2, 3, 1])
y = np.array([[1, 2, 3], [5, 6, 1]])
x.mean()

1.75

In [35]:
np.median(x)

1.5

In [36]:
np.median(y, axis=-1) # last axis

array([2., 5.])

In [37]:
x.std()          # full population standard dev.

0.82915619758885

# Array Shape Manipulation

**Flattening**

In [41]:
a = np.array([[1, 2, 3], [4, 5, 6]])
a.ravel() #Return a contiguous flattened array. A 1-D array, containing the elements of the input, is returned. A copy is made only if needed.

array([1, 2, 3, 4, 5, 6])

In [44]:
print(a)
print()
a.T #Transpose

[[1 2 3]
 [4 5 6]]



array([[1, 4],
       [2, 5],
       [3, 6]])

In [45]:
a.T.ravel()

array([1, 4, 2, 5, 3, 6])

**Reshaping**

The inverse operation to flattening:

In [46]:
print(a.shape)
print(a)

(2, 3)
[[1 2 3]
 [4 5 6]]


In [47]:
b = a.ravel()
print(b)

[1 2 3 4 5 6]


In [48]:
b = b.reshape((2, 3))
b

array([[1, 2, 3],
       [4, 5, 6]])

**Adding a Dimension**

Indexing with the np.newaxis object allows us to add an axis to an array

newaxis is used to increase the dimension of the existing array by one more dimension, when used once. Thus,

1D array will become 2D array

2D array will become 3D array

3D array will become 4D array and so on

In [52]:
z = np.array([1, 2, 3])
z

array([1, 2, 3])

In [53]:
z[:, np.newaxis]

array([[1],
       [2],
       [3]])

**Dimension Shuffling**

In [59]:
a = np.arange(4)
print(a)
a = a.reshape(2,2)
print(a)
a.shape

[0 1 2 3]
[[0 1]
 [2 3]]


(2, 2)

In [60]:
a

array([[0, 1],
       [2, 3]])

**Resizing**

In [62]:
a = np.arange(4)
print(a)
a.resize((8,))
a

[0 1 2 3]


array([0, 1, 2, 3, 0, 0, 0, 0])

**Sorting Data**

In [65]:
#Sorting along an axis:
a = np.array([[5, 4, 6], [2, 3, 2]])
b = np.sort(a, axis=1) #axis 1 refers to column
b

array([[4, 5, 6],
       [2, 2, 3]])